### ISSUE TITLE
Cannot ping 10.0.14.2

### ISSUE THREAD

**Issue by jiahao-shen** [netgroup/SDN-TE-SR-tools#1]
After i run the command`./sr_vll_pusher.py --controller 10.255.245.1:8080 --add`,it runs successfully.
But when i log in `ssh -X root@10.255.247.1`, i cannot ping 10.0.14.2.

**Comment by pierventre** [comment]
It is hard to say what is happening. Please write on the mailing of the project (https://groups.google.com/forum/#!forum/oshi-list) and we will try to troubleshoot the problem.

I would suggest also to use the ready-to-go VBox image.
